name: catmap_env
channels:
  - conda-forge
dependencies:
  - python=3.12
  - streamlit=1.43.2
  - plotly=5.24.1
  - numpy=1.26.4
  - pandas=2.2.2
  - scipy=1.14.1
  - scikit-learn=1.5.2
  - anndata=0.11.3
  - scanpy=1.11.0
  - scvi-tools=1.3.0
  - jax=0.4.31
  - jaxlib=0.4.31
  - pylint=3.3.3
  - python-build=1.2.2
  - pip=25.0
  - pytorch=2.4
