name: catmap_env
channels:
  - defaults
  - conda-forge
dependencies:
  - jupyter=1
  - notebook=7
  - python>=3.10
  - streamlit=1.42
  - plotly=6
  - numpy=2.2
  - pandas=2.2
  - pylint=3.3.3
  - build=0.10.0
  - pip
